# Generated by Django 3.1.5 on 2021-01-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_listitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='test',
            new_name='text',
        ),
    ]
